zitadel:
  masterkeySecretName: 'masterkey'
  configmapConfig:
    ExternalSecure: false
    ExternalDomain: access.netsnek.com
    TLS:
      Enabled: false
    Database:
      Cockroach:
        Host: db-cockroachdb-public
        User:
          SSL:
            Mode: verify-full
        Admin:
          SSL:
            Mode: verify-full
  secretConfig:
    Database:
      Cockroach:
        User:
          Password: xyz
        Admin:
          Password: abc

  dbSslCaCrtSecret: db-cockroachdb-ca-secret
  dbSslAdminCrtSecret: db-cockroachdb-client-secret
  dbSslUserCrtSecret: db-cockroachdb-zitadel-secret
